In [1]:
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
class Kmeans:
    
    def __init__(self, X, K, beta):
        self.X = X
        self.K = K
        self.beta = beta
        self.N,self.D = X.shape
        idx = np.random.permutation(self.N)[:K]
        self.m = X.copy()[idx]
        
    def distance2(self):
        

In [5]:
X = (np.random.randn(5,2) * 100) // 3
X,X.shape

(array([[-46., -48.],
        [ 15., -20.],
        [-10., -30.],
        [ 48.,  34.],
        [ 31.,  -8.]]), (5, 2))

In [6]:
m = (np.random.randn(2,2) * 100) // 3
m,m.shape

(array([[-23.,  17.],
        [-34.,  51.]]), (2, 2))

In [7]:
diff = X - m.reshape([2,1,2])
diff,diff.shape

(array([[[-23., -65.],
         [ 38., -37.],
         [ 13., -47.],
         [ 71.,  17.],
         [ 54., -25.]],
 
        [[-12., -99.],
         [ 49., -71.],
         [ 24., -81.],
         [ 82., -17.],
         [ 65., -59.]]]), (2, 5, 2))